train:
  epochs: 1500
  batch_size: 128
  eval_batch_size: 512
  lr: 0.0005

diffusion:
  layers: 5
  channels: 512
  nheads: 2
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 60
  schedule: "quad"
  mixed: True
  token_emb_dim: 1 # refers to tokenizer

model:
  task: onehot
  is_unconditional: 0
  timeemb: 128
  featureemb: 7
  target_strategy: "random"

sample:
  m: 1