model:
  hint_rate: 0.85

train:
  epochs: 50000
  batch_size: 128
  loss:
    alpha: 400
    beta: 60
  Adam:
    lr: 0.005
    betas_g: [0.9, 0.999]
    betas_d: [0.9, 0.999]
    weight_decay: 0.0001
